### ISSUE TITLE
ZIP file

### ISSUE THREAD

**Issue by xxsimoxx** [tradesouthwest/flexline#1]
In the current release the theme expands to a folder named `1.0.4a` and that causes problems with installation and deletion.

If you like automatic generation of the ZIP file built using GitHub actions upon release (you have to correctly tag the release) you can use [the action](https://github.com/ClassicPress/classicpress-directory-integration/blob/main/.github/workflows/build.yml) used by our Directory Integration plugin.

**Comment by tradesouthwest** [comment]
For uploading zip I was told to pack the folder with theme name that contains the them files in it. I will try again. Otherwise I can look at the script you offer in last thread. I am not sure the script would be very helpful since I am not a .yml expert by any means.

**Comment by tradesouthwest** [comment]
Added new folder as `flexline` and updated url in directory.

**Comment by tradesouthwest** [comment]
Will let you close this if you have time to check new Release. I did verify and it downloads from directory as `flexline` :-)

**Comment by xxsimoxx** [comment]
ZIP file is now correct! Consider also change theme version to reflect the tag.
